language: node_js
node_js: node
sudo: true
addons:
  google-chrome: latest
stages:
  - name: test
  - name: release
    if: branch = master and type = push
jobs:
  include:
    - stage: test
      script: xvfb-run npm test && cat ./coverage/lcov.info | coveralls
    - stage: release
      script: npm run build && semantic-release
