language: node_js
node_js: node
stages:
  - name: test
  - name: release
    if: branch = master and type = push
jobs:
  include:
    - stage: test
      script: npm test && cat ./coverage/lcov.info | coveralls
    - stage: release
      script: semantic-release
notifications:
  email:
    on_success: never
